name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v5

    - name: Install uv and set the Python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Run ruff check
      run: |
        uvx ruff check

    - name: Run ruff format check
      run: |
        uvx ruff format --check

    - name: Run ty type checker
      run: |
        uvx ty check

    - name: Run tests
      run: |
        uv run pytest tests -v